### ISSUE TITLE
Zoeken API error when searching

### ISSUE THREAD

**Issue by fvaneeuwijk** [app-vise/kvk-api#2]
Fatal error: Uncaught Error: Using $this when not in object context

php 8.1

try {
    **$resultaten = $this->client->search($query);**
    foreach ($resultaten->getResultaten() as $searchResult) {
        // do something with $searchResult
    }
} catch(NotFoundException | ApiException $exception) {
    // handle error
}

**Comment by DaanGeurts** [comment]
If you use this library outside an object you cannot use $this because it's used to access members or functions of that object.
You should use something like the following:

```php
$rootCertificate = <location_of_root_certificate>;
$client = KvkClientFactory::create(<YOUR_API_KEY>, 'test | production', $rootCertificate);

$query = new SearchQuery();
$query->setKvkNumber('KVK nummer to search for');

try {
    $resultaten = $client->search($query);
    foreach ($resultaten->getResultaten() as $searchResult) {
        // do something with $searchResult
    }
} catch(NotFoundException | ApiException $exception) {
    // handle error
}
```

**Comment by DaanGeurts** [comment]
Does this solve your problem?

**Comment by fvaneeuwijk** [comment]
yes it's resolved
