### ISSUE TITLE
Hoe kan ik het adres van de hoofdvestiging ophalen?

### ISSUE THREAD

**Issue by Lauren076** [app-vise/kvk-api#3]
Hallo,

Ik probeer het adres gesplitst in straat, nummer, postcode, plaats etc op te halen van het hoofdadres. Dit lijkt echter niet mogelijk. Is dit simpelweg nog niet geimplementeerd in de package of zie ik iets over het hoofd? Als dit wel mogelijk is, hoe zou dit dan moeten?

Ik gebruik op dit moment de endpoint getBasisProfielHoofdVestiging maar hier kom ik niet echt verder mee.

Gr. Lauren

**Comment by DaanGeurts** [comment]
Hi Lauren,
there is a getVolledigAdres() method on the  [Adres](https://github.com/app-vise/kvk-api/blob/main/src/Model/Adres.php) object but also getStraatnaam(), getHuisnummer(), getPostcode() etc.
With these you can get the address parts separately.
Are you helped with my comment?

**Comment by Lauren076** [comment]
Hi Daan,

Thank you for your reply! Can you please explain to me how can I reach this Adres object? I tried the code below but that doesn't work. What is the correct syntax?

Like to hear from you!

```
$this->client = KvkClientFactory::create($this->apiKey, $this->stage, $rootCertificate = null);
$query = new ProfileQuery('33103545');

try {
    $baseProfile = $this->client->getBasisProfiel($query);

    $data = [
        'cocNumber' => $baseProfile->getKvkNummer(),
        'postcode' => $baseProfile->getPostcode(),
    ];
}

} catch(NotFoundException | ApiException $exception) {
    // handle error
}
```

**Comment by DaanGeurts** [comment]
This library is a simple wrapper around the KVK responses, so when fetching [BasisProfiel](https://github.com/app-vise/kvk-api/blob/main/src/Model/Company/BasisProfiel.php), you don't get any addresses within that response but you can get an [EmbeddedContainer](https://github.com/app-vise/kvk-api/blob/main/src/Model/Company/EmbeddedContainer.php) object which can hold [Eigenaar](https://github.com/app-vise/kvk-api/blob/main/src/Model/Company/Eigenaar.php) en [Vestigings](https://github.com/app-vise/kvk-api/blob/main/src/Model/Company/Vestiging.php) object and [Vestigings](https://github.com/app-vise/kvk-api/blob/main/src/Model/Company/Vestiging.php) object has addresses to it via getAdressen().
One footnote, all these objects can be null

**Comment by Lauren076** [comment]
Thank you Daan, its working!
